export async function login() {
  try {
  } catch (err: unknown) {
    console.error('login error', err);
  }
}
